### ISSUE TITLE
User role's related code should be commented

### ISSUE THREAD

**Issue by phongvq** [lqmanh/fastapi-app#3]
User role hasn't been implemented yet, thus it should be commented out to avoid error when starting app.
https://github.com/lqmanh/fastapi-app/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/modules/users/users_models.py#L10

**Comment by lqmanh** [comment]
Fixed in 7e942f3.
