### ISSUE TITLE
Path resolution on first lunch

### ISSUE THREAD

**Issue by sid3r** [lqmanh/fastapi-app#4]
Hello, I've just copied the project files using **cookiecutter** for testing, I've trouble lunching the server: how am I supposed to serve the project using poetry? 

.env:
```
PYTHON_ENV=
ROOT_PATH=
```

the command  `
poetry run python api/server.py
` return the error: 

```
Traceback (most recent call last):
  File "/Users/mac/document-ocr/api/api/server.py", line 9, in <module>
    from api.config import settings
ModuleNotFoundError: No module named 'api'
```

any help is welcome.

**Comment by lqmanh** [comment]
Which version of Python and Poetry you're using?

**Comment by sid3r** [comment]
@lqmanh python 3.9.1, poetry 1.1.5

**Comment by lqmanh** [comment]
@sid3r That's weird. I use nearly the same version for both of them and it works fine. I use Linux, but I doubt there's any difference on MacOS though.

It looks like you generated the app inside a bigger project or something? Could you please try to generate another app to another place?

**Comment by sid3r** [comment]
@lqmanh Indeed I'm on MacOS, Just did that, I reinstalled the package in a fresh folder, the same error is still showing :/

**Comment by sid3r** [comment]
@lqmanh Since there's no visible error nor explanation to this issue, I'm closing it. I've made my proper project with the same packages and it works fine.
